# Generated by Django 3.2.6 on 2022-01-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
