# Generated by Django 3.2.6 on 2022-01-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
    ]
