# Generated by Django 3.2.6 on 2022-01-11 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 11, 7, 7, 13, 704710)),
        ),
    ]
