# Generated by Django 3.2.6 on 2022-01-11 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 11, 50, 53, 369467)),
        ),
    ]
